### ISSUE TITLE
You should be able to set database file used (Lawnchair adapter)

### ISSUE THREAD

**Issue by vojto** [davibe/Phonegap-SQLitePlugin#1]
In some cases, it's convenient to use one database file per table, as in [current implementation](https://github.com/davibe/Phonegap-SQLitePlugin/blob/master/src/lawnchair_pgsqlite_plugin_adapter.js.coffee#L27). 

But a typical SQLite application would open one database file, and create multiple tables in it. 

Such behavior is not currently possible, but could be easily added, since it is possible to pass options to Lawnchair constructor and these options are then forwarded to the adapter. There could be an option called `db` or `database` that would be used to set name for database file.

**Is there any reason for creating database files one per table?**

If not, I will send you a pull request.

**Comment by davibe** [comment]
There is no reason and I would prefer to use one single database so yes, open a pull request :)
