### ISSUE TITLE
SQLitePlugin Fails after 1000 transactions on iOS

### ISSUE THREAD

**Issue by n8sabes** [davibe/Phonegap-SQLitePlugin#33]
Execute 1000 "transactions" sequentially and the app freezes up preventing further Sqlite calls. Completion functions are no longer called after 500~1000 cycles causing the freeze. Here is an example of the problem:

https://github.com/n8sabes/ionic-sqlite-1000-transactions-ios-bug

Any input on the cause / fix would be appreciated.

**Comment by davibe** [comment]
You are using Cordova-SQLitePlugin implementation from "brodysoft" github user. I suggest you refer to him.

**Comment by n8sabes** [comment]
Thank you. I posted the question on brodysoft's project as well.

NOTE -- I just rebuilt the example (replacing the SQLite plugin with your plugin) and the same issue occurs only the cycles before failure are >1500. Can you try to cycling 1500+ sequential transactions (with or without an INSERT within it) on the iOS simulator and see what your results are? My completion functions stop being called and then the SQLite plugin goes deaf.

I've been chasing this (bug?) all day and welcome any thoughts on the issue.

I'm running iOS 8.1 (12B411)
