### ISSUE TITLE
PGSQLitePlugin.h calls for resource that doesn't exist.

### ISSUE THREAD

**Issue by stevoyoung** [davibe/Phonegap-SQLitePlugin#7]
PGSQLitePlugin.h tries to import "PhoneGap/JSON.h", which doesn't exist in PhoneGap 1.4.1. There is a "JSONKit.h" that exist but when I switch it out for that file I get a load of errors when I try to compile my app.

**Comment by stevoyoung** [comment]
Look like is should have read some more. this eels to be addressed on the front page.

**Comment by davibe** [comment]
Try to understand what other built in phonegap modules use instead of
the older json.h

It can't be too much different! :)

I do not have time to look at it soon

## 

Davide Bertola (from iPhone)

Il giorno 10/feb/2012, alle ore 00:23, stevoyoung
reply@reply.github.com
ha scritto:

**Comment by stevoyoung** [comment]
Thanks for the reply, Davide. 

I got it working by following your instructions at the top of the read me file. For some reason, my local read me didn't have those instructions -  that's how I missed it.

Thanks for the work on this plugin.
